/* ============================================================
   ELEGANT CONSTRUCTION — Gallery Page JavaScript
   ============================================================ */

// Force page to scroll to top on refresh
if (history.scrollRestoration) {
  history.scrollRestoration = 'manual';
}
window.scrollTo(0, 0);

document.addEventListener('DOMContentLoaded', () => {

  // ─── Page Loader ────────────────────────────────────────────
  const pageLoader = document.getElementById('pageLoader');
  if (pageLoader) {
    pageLoader.classList.add('hidden');
    setTimeout(() => pageLoader.remove(), 500);
  }

  // ─── Sticky Header ─────────────────────────────────────────
  const header = document.getElementById('header');
  const topBar = document.querySelector('.top-bar');
  let topBarHeight = topBar ? topBar.offsetHeight : 0;

  function handleScroll() {
    if (window.scrollY > topBarHeight + 10) {
      header.classList.add('scrolled');
    } else {
      header.classList.remove('scrolled');
    }
  }

  window.addEventListener('scroll', handleScroll, { passive: true });
  handleScroll();

  // ─── Mobile Menu Toggle ────────────────────────────────────
  const mobileToggle = document.getElementById('mobileToggle');
  const navLinks = document.getElementById('navLinks');

  if (mobileToggle && navLinks) {
    mobileToggle.addEventListener('click', () => {
      mobileToggle.classList.toggle('active');
      navLinks.classList.toggle('active');
      document.body.style.overflow = navLinks.classList.contains('active') ? 'hidden' : '';
    });

    navLinks.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        mobileToggle.classList.remove('active');
        navLinks.classList.remove('active');
        document.body.style.overflow = '';
      });
    });
  }

  // ─── Gallery State ─────────────────────────────────────────
  let galleryItems = [];
  let filteredItems = [];
  let currentFilter = 'all';
  let lightboxIndex = 0;

  const galleryGrid = document.getElementById('galleryGrid');
  const galleryLoading = document.getElementById('galleryLoading');
  const galleryCounter = document.getElementById('galleryCounter');
  const galleryCountNum = document.getElementById('galleryCountNum');

  // ─── Load Gallery Data ─────────────────────────────────────
  // GALLERY_DATA is loaded from gallery-data.js (auto-generated by GitHub Actions)
  function loadGallery() {
    // Hide loading spinner
    if (galleryLoading) galleryLoading.style.display = 'none';

    let combined = [];
    if (typeof GALLERY_DATA !== 'undefined' && GALLERY_DATA.length > 0) {
      combined = [...GALLERY_DATA];
    }

    // Fetch remote videos automatically
    fetch('remote-videos.json')
      .then(res => res.json())
      .catch(() => [])
      .then(remoteItems => {
        if (remoteItems && Array.isArray(remoteItems) && remoteItems.length > 0) {
          remoteItems.forEach(item => {
             let url = item.url || item.file;
             if(url && url.includes('dropbox.com')) {
               url = url.replace('dl=0', 'raw=1').replace('dl=1', 'raw=1');
               if (!url.includes('raw=1')) url += url.includes('?') ? '&raw=1' : '?raw=1';
             }
             combined.push({ file: url, title: item.title || 'Dropbox Video', type: 'video' });
          });
        }
        
        if (combined.length > 0) {
          galleryItems = combined;
          filteredItems = [...galleryItems];
          renderGallery();
          updateCounter();
        } else {
          showEmptyState();
        }
      });
  }

  // ─── Render Gallery Cards ──────────────────────────────────
  function renderGallery() {
    if (!galleryGrid) return;
    galleryGrid.innerHTML = '';

    if (filteredItems.length === 0) {
      showEmptyState();
      return;
    }

    filteredItems.forEach((item, index) => {
      const card = document.createElement('div');
      card.className = 'gallery-card';
      card.setAttribute('data-index', index);
      card.style.animationDelay = `${Math.min(index * 0.05, 0.6)}s`;

      const isVideo = item.type === 'video';

      card.innerHTML = `
        <div class="gallery-card-media">
          ${isVideo ? `
            <video src="${item.file}" muted loop preload="metadata"></video>
            <div class="gallery-card-play"><i class="fas fa-play"></i></div>
          ` : `
            <img src="${item.file}" alt="${item.title}" loading="lazy">
          `}
          <span class="gallery-card-badge">
            <i class="fas fa-${isVideo ? 'video' : 'camera'}"></i>
            ${isVideo ? 'Video' : 'Photo'}
          </span>
          <div class="gallery-card-overlay">
            <div class="gallery-card-overlay-icon">
              <i class="fas fa-${isVideo ? 'play' : 'expand'}"></i>
            </div>
          </div>
        </div>
        <div class="gallery-card-info">
          <h3>${item.title}</h3>
          <div class="gallery-card-type"><i class="fas fa-${isVideo ? 'film' : 'image'}"></i> ${isVideo ? 'Video' : 'Photo'}</div>
        </div>
      `;

      // Open lightbox on click
      card.addEventListener('click', () => {
        lightboxIndex = index;
        openLightbox();
      });

      // Auto-play video preview on hover
      if (isVideo) {
        const videoEl = card.querySelector('video');
        card.addEventListener('mouseenter', () => {
          videoEl.play().catch(() => {});
        });
        card.addEventListener('mouseleave', () => {
          videoEl.pause();
          videoEl.currentTime = 0;
        });
      }

      galleryGrid.appendChild(card);
    });
  }

  // ─── Filter Buttons ────────────────────────────────────────
  const filterBtns = document.querySelectorAll('.gallery-filter-btn');
  filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      // Update active state
      filterBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      currentFilter = btn.getAttribute('data-filter');

      if (currentFilter === 'all') {
        filteredItems = [...galleryItems];
      } else {
        filteredItems = galleryItems.filter(item => item.type === currentFilter);
      }

      renderGallery();
      updateCounter();
    });
  });

  // ─── Update Counter ────────────────────────────────────────
  function updateCounter() {
    if (galleryCountNum) {
      galleryCountNum.textContent = filteredItems.length;
    }
    if (galleryCounter) {
      galleryCounter.style.display = filteredItems.length > 0 ? 'block' : 'none';
    }
  }

  // ─── Empty State ───────────────────────────────────────────
  function showEmptyState() {
    if (!galleryGrid) return;
    galleryGrid.innerHTML = `
      <div class="gallery-empty" style="grid-column: 1 / -1;">
        <div class="gallery-empty-icon"><i class="fas fa-images"></i></div>
        <h3>Gallery Coming Soon</h3>
        <p>Our team is curating the best project photos and videos. Check back soon to see our latest achievements and milestones.</p>
      </div>
    `;
    if (galleryCounter) galleryCounter.style.display = 'none';
  }

  // ─── Lightbox ──────────────────────────────────────────────
  const lightbox = document.getElementById('lightbox');
  const lightboxMediaContainer = document.getElementById('lightboxMedia');
  const lightboxTitle = document.getElementById('lightboxTitle');
  const lightboxCounterEl = document.getElementById('lightboxCounter');
  const lightboxClose = document.getElementById('lightboxClose');
  const lightboxPrev = document.getElementById('lightboxPrev');
  const lightboxNext = document.getElementById('lightboxNext');

  function openLightbox() {
    if (!lightbox) return;
    updateLightboxContent();
    lightbox.classList.add('active');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    if (!lightbox) return;
    lightbox.classList.remove('active');
    document.body.style.overflow = '';

    // Pause any playing video
    const video = lightboxMediaContainer.querySelector('video');
    if (video) video.pause();
  }

  function updateLightboxContent() {
    if (!lightboxMediaContainer || filteredItems.length === 0) return;

    const item = filteredItems[lightboxIndex];
    const isVideo = item.type === 'video';

    // Pause any currently playing video
    const existingVideo = lightboxMediaContainer.querySelector('video');
    if (existingVideo) existingVideo.pause();

    if (isVideo) {
      lightboxMediaContainer.innerHTML = `
        <video class="lightbox-media-video" src="${item.file}" controls autoplay></video>
      `;
    } else {
      lightboxMediaContainer.innerHTML = `
        <img class="lightbox-media" src="${item.file}" alt="${item.title}">
      `;
    }

    if (lightboxTitle) lightboxTitle.textContent = item.title;
    if (lightboxCounterEl) lightboxCounterEl.textContent = `${lightboxIndex + 1} of ${filteredItems.length}`;
  }

  function navigateLightbox(direction) {
    lightboxIndex = (lightboxIndex + direction + filteredItems.length) % filteredItems.length;
    updateLightboxContent();
  }

  // Lightbox event listeners
  if (lightboxClose) lightboxClose.addEventListener('click', closeLightbox);
  if (lightboxPrev) lightboxPrev.addEventListener('click', () => navigateLightbox(-1));
  if (lightboxNext) lightboxNext.addEventListener('click', () => navigateLightbox(1));

  // Click backdrop to close
  const lightboxBackdrop = document.querySelector('.lightbox-backdrop');
  if (lightboxBackdrop) lightboxBackdrop.addEventListener('click', closeLightbox);

  // Keyboard navigation
  document.addEventListener('keydown', (e) => {
    if (!lightbox || !lightbox.classList.contains('active')) return;

    switch (e.key) {
      case 'Escape':
        closeLightbox();
        break;
      case 'ArrowLeft':
        navigateLightbox(-1);
        break;
      case 'ArrowRight':
        navigateLightbox(1);
        break;
    }
  });

  // ─── Initialize ────────────────────────────────────────────
  loadGallery();

});
