/* Gallery Data — Auto-generated by GitHub Actions */
/* To add images: upload photos/videos to the gallery/ folder on GitHub */
/* The GitHub Action will regenerate this file automatically */
/* 
   File naming tip: Use descriptive names with hyphens or underscores.
   Example: "luxury-home-irvine.jpg" becomes title "Luxury Home Irvine"
*/

const GALLERY_DATA = [
  {"file": "images/project1.png", "title": "Luxury Residential Estate", "type": "image"},
  {"file": "images/project2.png", "title": "Corporate Office Complex", "type": "image"},
  {"file": "images/project3.png", "title": "Municipal Infrastructure", "type": "image"},
  {"file": "images/commercial.png", "title": "Commercial Construction", "type": "image"},
  {"file": "images/residential.png", "title": "Residential Construction", "type": "image"},
  {"file": "images/public-works.png", "title": "Public Works Project", "type": "image"}
];
